name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [jdk, graalvm]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Test in Linux JDK
        if: matrix.os == 'ubuntu-latest' && matrix.java == 'jdk'
        run: docker-compose -f docker/Linux-JDK11/docker-compose.yml up --exit-code-from cantaloupe
      - name: Test in Linux GraalVM
        if: matrix.os == 'ubuntu-latest' && matrix.java == 'graalvm'
        run: docker-compose -f docker/Linux-GraalVM20/docker-compose.yml up --exit-code-from cantaloupe
      - name: Test in Windows JDK
        if: matrix.os == 'windows-latest' && matrix.java == 'jdk'
        run: docker-compose -f docker/Windows10-JDK11/docker-compose.yml up --exit-code-from cantaloupe
      - name: Test in Windows JDK
        if: matrix.os == 'windows-latest' && matrix.java == 'graalvm'
        # TODO: Windows+GraalVM
        run: echo "Windows+GraalVM isn't working yet"
